TrueLayer/truelayer-signing

csharp/src/Verifier.cs, csharp/test/ErrorTest.cs, csharp/test/UsageTest.cs, javascript/lib/lib.js, javascript/test/usage.js, rust/tests/usage.rs
Signatures are supposed to have detached bodies. We then populate the body during verification. However, if you send jws with an attached valid body, that otherwise would have failed validation the C# verify logic allowed it, as `.Replace("..", ...)` silently did nothing.
This pr fixes that, the C# lib requires detached jws signatures or throws a `SignatureException`.
Nodejs & rust were not vulnerable to this, but now have similar scenario tests to cover this.
I also found the nodejs & C# verifiers were requiring at least some headers. Otherwise they would fail requiring the empty string `""` header. All 3 langs now have scenarios ensuring that no-header usage is allowed.
=> Fix C# allowing signatures with attached bodies + support C# & nodejs no-header usage

csharp/CHANGELOG.md, csharp/src/Util.cs, csharp/src/Verifier.cs, csharp/test/ErrorTest.cs, javascript/CHANGELOG.md
C# verify currently throws `System.Collections.Generic.KeyNotFoundException` if required jws header fields are missing, such as `tl_version` or `alg`. This pr instead throws `SignatureException` to handle these simply as invalid signatures.
=> C# throw SignatureException for missing jws headers

go/CHANGELOG.md, go/tlsigning_test.go, go/verify/verifier.go
As title says, removed verifier's method default value to conform to other implementations.
=> Removed verifier's method default value and wrote a test for it.

rust/src/jws.rs, rust/src/sign.rs, rust/tests/usage.rs
When signing webhooks we want to also include a `jku` JSON Web Key URL which will be used to lookup the jwk public key to verify webhooks.
This PR supports adding a `jku` when signing & extracting it out of a signature using the rust lib. The former does not need wide support as clients will not need to set `jku` for regular requests. We should probably add extracting the jku to all langs though.
This is a non-breaking change.
=> rust: support `jku` jws header

csharp/CHANGELOG.md, csharp/src/Util.cs, csharp/src/Verifier.cs, csharp/test/ErrorTest.cs, csharp/test/UsageTest.cs, csharp/test/truelayer-signing.test.csproj
Adds methods to allow extracting webhook signature `jku` and verify using the jwks response data directly.
See #23 for motivating details.
```cs
var jku = Verifier.ExtractJku(webhookSignature);
```
```cs
Verifier.VerifyWithJwks(jwks)
.Method("POST")
.Path("/tl-webhook")
.Header("x-tl-webhook-timestamp", "2021-11-29T11:42:55Z")
.Header("content-type", "application/json")
.Body("{\"event_type\":\"example\",\"event_id\":\"18b2842b-a57b-4887-a0a6-d3c7c36f1020\"}")
.Verify(webhookSignature); // throws SignatureException if invalid
```
=> C# Add `Verifier.VerifyWithJwks`, `Verifier.ExtractJku`

csharp/CHANGELOG.md, csharp/src/Verifier.cs, csharp/test/ErrorTest.cs, go/tlsigning_test.go, java/lib/build.gradle, java/lib/src/test/java/truelayer/signing/UsageTest.java, nodejs/src/__tests__/usage.test.ts, rust/tests/usage.rs
JWE tokens may have trailing dots, which can potentially cause issue with some `replace("..")` logic with pre-attached bodies.
=> Add pre-attached trailing dots test scenarios

nodejs/CHANGELOG.md, nodejs/README.md, nodejs/jestconfig.json, nodejs/package.json, nodejs/src/__tests__/usage.test.js, nodejs/src/__tests__/usage.test.ts, nodejs/src/lib.ts, nodejs/yarn.lock
Allow extracting webhook signature jku and verify using the jwks response data.
See #23 for motivating details.
Also:
* Update arg type field nullability
* Add verify example to readme
* Update dependencies
* Add node_modules to jest ignore
I aim to release this as **0.1.2**.
The `verify` function may be used to verify webhook `Tl-Signature` header signatures.
```javascript
const tlSigning = require('truelayer-signing');
let jku = tlSigning.extractJku(webhookSignature);
// fetch jwks JSON from the `jku` url.
let jwks = fetch_jwks(jku);
// jwks may be used directly to verify a signature
// a SignatureError is thrown is verification fails
tlSigning.verify({
jwks,
signature: webhookSignature,
method: "post",
path,
body,
headers,
});
```
=> nodejs: Add `verify` support for `jwks`

csharp/README.md, nodejs/README.md, rust/README.md
Adds rust & C# verify webhook snippet examples to their READMEs. Also update the nodejs one.
=> Add verifying webhooks readme examples

csharp/CHANGELOG.md, csharp/src/Verifier.cs, csharp/src/truelayer-signing.csproj, go/CHANGELOG.md, go/crypto/crypto.go, java/CHANGELOG.md, java/lib/src/main/java/truelayer/signing/VerifierFromJwks.java, rust/CHANGELOG.md, rust/Cargo.toml, rust/src/openssl.rs, test-resources/jwks.json
Referring to https://datatracker.ietf.org/doc/html/draft-ietf-jose-json-web-algorithms#section-3.1 our EC jwk.alg field should actually be `ES512` rather than `EC`.
This pr adds support for that without breaking the existing alg value, since this field isn't strictly required anyway.
Affects langs: **rust, go, java, csharp**
=> Support jwk.alg being "ES512"

csharp/README.md, nodejs/README.md, rust/README.md
Update the examples to hint that webhook verification should add all headers to the verifier.
=> Update node,c#,rust verify webhook snippets

.github/workflows/java.yml, java/build.gradle, java/gradle.properties, java/lib/build.gradle, java/lib/publish.gradle, java/lib/src/main/java/com/truelayer/signing/CheckedSupplier.java, java/lib/src/main/java/com/truelayer/signing/HeaderName.java, java/lib/src/main/java/com/truelayer/signing/KeyException.java, java/lib/src/main/java/com/truelayer/signing/SignatureException.java, java/lib/src/main/java/com/truelayer/signing/Signer.java, java/lib/src/main/java/com/truelayer/signing/Utils.java, java/lib/src/main/java/com/truelayer/signing/Verifier.java, java/lib/src/main/java/com/truelayer/signing/VerifierFromJwks.java, java/lib/src/main/java/com/truelayer/signing/VerifierFromPublicKey.java, java/lib/src/test/java/com/truelayer/signing/UsageTest.java, java/lib/test.gradle, java/settings.gradle, jitpack.yml
This PR adds:
- Release workflow. Push to maven central only if the `gradle.properties` version attribute changed from the previous commit. It will just close the staging repository at first, so promotion will be manual.
- Move package `truelayer.signing` to `com.truelayer.signing`
When merged it will not trigger a release.
I will do another PR with Changelog changes and version set to `0.2.0`.
=> Move under com.truelayer and define release pipeline

README.md, csharp/README.md, go/README.md, java/README.md, nodejs/README.md, rust/README.md
An important part of verifying a webhook signature is checking that the `jku` is an expected TrueLayer url. So we should hint at that in README snippets as well as include it in full examples like #47 
You could argue that it was already part of the not-included-here `fetchJwks(jku)` impl, but I think it's important enough that we should drive the point home by explicitly mentioning it.
=> Hint jku allowlist in webhook snippets + mention webhook verification in top-level readme

.github/workflows/rust.yml, rust/README.md, rust/examples/webhook-server/Cargo.toml, rust/examples/webhook-server/README.md, rust/examples/webhook-server/src/main.rs
#47 for Rust, including jwks fetch caching.
A http server than can receive and verify signed TrueLayer webhooks.
Run the server.
```sh
RUST_LOG=info cargo run
```
Send a valid webhook that was signed for path `/hook/d7a2c49d-110a-4ed2-a07d-8fdb3ea6424b`.
```sh
curl -iX POST -H "Content-Type: application/json" \
-H "X-Tl-Webhook-Timestamp: 2022-03-11T14:00:33Z" \
-H "Tl-Signature: eyJhbGciOiJFUzUxMiIsImtpZCI6IjFmYzBlNTlmLWIzMzUtNDdjYS05OWE5LTczNzQ5NTc1NmE1OCIsInRsX3ZlcnNpb24iOiIyIiwidGxfaGVhZGVycyI6IngtdGwtd2ViaG9vay10aW1lc3RhbXAiLCJqa3UiOiJodHRwczovL3dlYmhvb2tzLnRydWVsYXllci5jb20vLndlbGwta25vd24vandrcyJ9..AE_QsBRhnsMkcRzd42wvY1e2HruUhkOgjuZKktGH_WmbD7rBzoaEHUuF36IxyyvCbLajd3MBExNmzjbrOQsGaspwAI5DcGVMFLKUhB7ZzUlTP9up3eNUrdwWyyfBWDQb-qmEuLnrhFDJvgCXEqlV5OLrt-O7LaRAJ4f9KHsZLQ_j2vPC" \
-d …
```
=> Add Rust webhook server example

.github/workflows/csharp.yml, csharp/.gitignore, csharp/README.md, csharp/examples/webhook-server/ExampleWebhookServer.csproj, csharp/examples/webhook-server/Program.cs, csharp/examples/webhook-server/README.md, csharp/examples/webhook-server/Startup.cs, csharp/examples/webhook-server/WebhookController.cs
#47 for C#
A http server than can receive and verify signed TrueLayer webhooks.
Run the server.
```sh
dotnet run
```
Send a valid webhook that was signed for path `/hook/d7a2c49d-110a-4ed2-a07d-8fdb3ea6424b`.
```sh
curl -iX POST -H "Content-Type: application/json" \
-H "X-Tl-Webhook-Timestamp: 2022-03-11T14:00:33Z" \
-H "Tl-Signature: eyJhbGciOiJFUzUxMiIsImtpZCI6IjFmYzBlNTlmLWIzMzUtNDdjYS05OWE5LTczNzQ5NTc1NmE1OCIsInRsX3ZlcnNpb24iOiIyIiwidGxfaGVhZGVycyI6IngtdGwtd2ViaG9vay10aW1lc3RhbXAiLCJqa3UiOiJodHRwczovL3dlYmhvb2tzLnRydWVsYXllci5jb20vLndlbGwta25vd24vandrcyJ9..AE_QsBRhnsMkcRzd42wvY1e2HruUhkOgjuZKktGH_WmbD7rBzoaEHUuF36IxyyvCbLajd3MBExNmzjbrOQsGaspwAI5DcGVMFLKUhB7ZzUlTP9up3eNUrdwWyyfBWDQb-qmEuLnrhFDJvgCXEqlV5OLrt-O7LaRAJ4f9KHsZLQ_j2vPC" \
-d …
```
=> Add C# webhook server example

.github/workflows/csharp.yml, csharp/README.md, csharp/examples/sign-request/ExampleSignRequest.csproj, csharp/examples/sign-request/Program.cs, csharp/examples/sign-request/README.md
#51 for C#
Sends a signed request to `https://api.truelayer-sandbox.com/test-signature`.
Set environment variables:
* `ACCESS_TOKEN` A valid JWT access token for `payments` scope [docs](https://docs.truelayer.com/docs/retrieve-a-token-in-your-server).
* `KID` The certificate/key UUID for associated with your public key uploaded to console.truelayer.com.
* `PRIVATE_KEY` Private key PEM string that matches the `KID` & uploaded public key.
Should have the same format as [this example private key](https://github.com/TrueLayer/truelayer-signing/blob/main/test-resources/ec512-private.pem).
```sh
$ dotnet run
Sending ...
204 ✓
```
=> Add C# request signature example

rust/.gitignore, rust/README.md, rust/examples/sign-request/Cargo.toml, rust/examples/sign-request/README.md, rust/examples/sign-request/src/main.rs
#51 for Rust
Sends a signed request to `https://api.truelayer-sandbox.com/test-signature`.
Set environment variables:
* `ACCESS_TOKEN` A valid JWT access token for `payments` scope [docs](https://docs.truelayer.com/docs/retrieve-a-token-in-your-server).
* `KID` The certificate/key UUID for associated with your public key uploaded to console.truelayer.com.
* `PRIVATE_KEY` Private key PEM string that matches the `KID` & uploaded public key.
Should have the same format as [this example private key](https://github.com/TrueLayer/truelayer-signing/blob/main/test-resources/ec512-private.pem).
```sh
$ cargo run
204 No Content ✓
```
=> [PAYG-723] Adds rust tl-signature example

csharp/CHANGELOG.md, csharp/src/Verifier.cs, csharp/src/truelayer-signing.csproj
Although all tests pass in CI, locally on my Macbook the `Verify_Jwks` tests fail for all targets other than .NET 5. For example the .NET Core 3.1 tests error with:
```
System.Security.Cryptography.CryptographicException
No OID value matches this name.
at System.Security.Cryptography.Oid.FromFriendlyName(String friendlyName, OidGroup group)
at System.Security.Cryptography.EccKeyFormatHelper.WriteEcParameters(ECParameters& ecParameters, AsnWriter writer)
at System.Security.Cryptography.EccKeyFormatHelper.WriteAlgorithmIdentifier(ECParameters& ecParameters, AsnWriter writer)
at System.Security.Cryptography.EccKeyFormatHelper.WriteSubjectPublicKeyInfo(ECParameters& ecParameters)
at System.Security.Cryptography.EccSecurityTransforms.ImportKey(ECParameters parameters)
at …
```
=> [dotnet] Fix VerifyWithJwks

.github/workflows/go.yml, go/examples/sign-request/README.md, go/examples/sign-request/go.mod, go/examples/sign-request/go.sum, go/examples/sign-request/main.go
#51 for Golang
Sends a signed request to `https://api.truelayer-sandbox.com/test-signature`.
Set environment variables:
* `ACCESS_TOKEN` A valid JWT access token for `payments` scope [docs](https://docs.truelayer.com/docs/retrieve-a-token-in-your-server).
* `KID` The certificate/key UUID for associated with your public key uploaded to console.truelayer.com.
* `PRIVATE_KEY` Private key PEM string that matches the `KID` & uploaded public key.
Should have the same format as [this example private key](https://github.com/TrueLayer/truelayer-signing/blob/main/test-resources/ec512-private.pem).
```sh
$ go run main.go
Sending...
204 ✓
```
=> [MAP-101] Add Golang request signature example

.github/workflows/go.yml, go/README.md, go/examples/webhook-server/README.md, go/examples/webhook-server/go.mod, go/examples/webhook-server/go.sum, go/examples/webhook-server/main.go
#47 for Golang, including jwks fetch caching.
A http server than can receive and verify signed TrueLayer webhooks.
Run the server.
```sh
go run main.go
```
Send a valid webhook that was signed for path `/hook/d7a2c49d-110a-4ed2-a07d-8fdb3ea6424b`.
```sh
curl -iX POST -H "Content-Type: application/json" \
-H "X-Tl-Webhook-Timestamp: 2022-03-11T14:00:33Z" \
-H "Tl-Signature: eyJhbGciOiJFUzUxMiIsImtpZCI6IjFmYzBlNTlmLWIzMzUtNDdjYS05OWE5LTczNzQ5NTc1NmE1OCIsInRsX3ZlcnNpb24iOiIyIiwidGxfaGVhZGVycyI6IngtdGwtd2ViaG9vay10aW1lc3RhbXAiLCJqa3UiOiJodHRwczovL3dlYmhvb2tzLnRydWVsYXllci5jb20vLndlbGwta25vd24vandrcyJ9..AE_QsBRhnsMkcRzd42wvY1e2HruUhkOgjuZKktGH_WmbD7rBzoaEHUuF36IxyyvCbLajd3MBExNmzjbrOQsGaspwAI5DcGVMFLKUhB7ZzUlTP9up3eNUrdwWyyfBWDQb-qmEuLnrhFDJvgCXEqlV5OLrt-O7LaRAJ4f9KHsZLQ_j2vPC" \
-d …
```
=> [MAP-24] Add Golang webhook server example

go/CHANGELOG.md, go/LICENSE-APACHE, go/LICENSE-MIT
Looks like `pkg.go.dev` is not happy to follow symlinks for license files.
=> [MAP-215] Provide license files instead of symlinks

.github/workflows/csharp.yml, .github/workflows/go.yml, .github/workflows/java.yml, .github/workflows/node.yml, .github/workflows/php.yml, .github/workflows/rust.yml, csharp/CHANGELOG.md, csharp/src/Signer.cs, csharp/src/Verifier.cs, csharp/src/truelayer-signing.csproj, csharp/test/ErrorTest.cs
=> C#: Add path arg validation to Signer & Verifier

csharp/README.md
.NET Standard 2.0 is supported however .NET Framework 4.6.x **is not** as it's missing required cryptography libraries. For .NET Framework use 4.7.x or higher.
=> Add C# netstandard2.0 compatibility note to readme

go/CHANGELOG.md, go/errors/errors.go, go/sign/signer.go, go/tlsigning_test.go, go/verify/verifier.go
https://github.com/TrueLayer/truelayer-signing/issues/69 for Golang
=> Golang: Add path arg validation to Signer & Verifier

go/CHANGELOG.md, go/jws/jws_header.go, go/sign/signer.go, go/tlsigning_test.go
This PR adds `Jku` method to `Signer` to allow different jku endpoints, just like `rust` implementation.
=> Golang: Add `Jku` method to `Signer`

nodejs/CHANGELOG.md, nodejs/package.json, nodejs/src/__tests__/usage.test.js, nodejs/src/lib.ts
Add validation that `body` is a string. This can otherwise silently produce a useless signature.
Resolves #84
=> nodejs: validate body string type

python/CHANGELOG.md, python/README.md, python/examples/webhook-server/main.py, python/poetry.lock, python/pyproject.toml, python/tests/test_tl_sign.py, python/truelayer_signing/__init__.py, python/truelayer_signing/sign.py, python/truelayer_signing/utils.py, python/truelayer_signing/verify.py
Adds and refactors to use JwsHeader type -- breaking change
Adds path validation to singer and verifier
Allows you to set the `jku` during the singing process
Bumps to `v0.2.0` from `v0.1.2`
Related issues: 
- #78 
- #69 
- #80
=> python:  adds path validation + jku to signer + path trailing slash

php/CHANGELOG.md, php/README.md, php/composer.json, php/src/AbstractJws.php, php/src/Contracts/Jws.php, php/src/Contracts/Verifier.php, php/src/Verifier.php, php/tests/SignerTest.php, php/tests/UtilTest.php, php/tests/VerifierTest.php
- Improve documentation especially for verifying webhook signatures
- Accept any header casing
- #80 option 2
- Fix workflow testing failing due to new Pest release
=> PHP-46: Signer improvements & fixes

.github/workflows/python.yml, python/poetry.lock, python/pyproject.toml
Broadens support for python to include v3.8.
Bumps to v0.2.2 from v0.2.1
Related issues:
#131
=> python: support python v3.8

.github/workflows/csharp.yml, README.md, csharp/README.md
Automate the release process by eliminating the needs for a manual release to NuGet.
The changes were tested [running the pipeline without merging the PR](https://github.com/TrueLayer/truelayer-signing/actions/runs/3912895731) in `main`: the result is a [conflicting push to NuGet](https://github.com/TrueLayer/truelayer-signing/actions/runs/3912895731/jobs/6688115243#step:5:12), which is expected since the version is the same as the one in the NuGet repository.
In a real case scenario that operation is expected to succeed.
Also adds guidelines on how to release the library in the [Wiki](https://github.com/TrueLayer/truelayer-signing/wiki/Versioning-and-Publishing#c).
=> [EWT-84] Improve release process - dotnet

ruby/examples/webhook-server/Gemfile, ruby/examples/webhook-server/main.rb
The ruby webhook server example introduced in https://github.com/TrueLayer/truelayer-signing/pull/148 does not work correctly. I am getting 401 - "Unauthorized" after doing all the steps from Readme.md
In the current PR, I've restored the broken ruby webhook server example. Related to https://github.com/TrueLayer/truelayer-signing/issues/177
The reason was incorrect `TrueLayerSigning` settings, and incorrect parsing of request headers.
- Introduced `ensure_certificate_id_present!` method which checks the certificate is present or assigns a random one. This fixed `TRUELAYER_SIGNING_CERTIFICATE_ID is missing` error from [truelayer-signing/ruby/lib/truelayer-signing/utils.rb](https://github.com/TrueLayer/truelayer-signing/blob/b64bb284f58b2d6a86622d18943c585744ff8ef3/ruby/lib/truelayer-signin …
=> Ruby: fix webhook server example

.github/workflows/ruby.yml, ruby/CHANGELOG.md, ruby/lib/truelayer-signing/jwt.rb, ruby/lib/truelayer-signing/signer.rb, ruby/lib/truelayer-signing/verifier.rb, ruby/test/test-truelayer-signing.rb, ruby/truelayer-signing.gemspec
The custom code patch we have for the `jwt` library, which prevents the payload object to be systematically parsed as JSON, breaks the original `JWT.encode` and `JWT.decode` methods. That's a problem for applications already using `JWT` for other purposes, since adding `truelayer-signing` suddenly causes unexpected errors.
This introduces the `JWT.truelayer_encode` and `JWT.truelayer_decode` methods, which allow us to modify the behaviour without compromising the underlying functionality. At some point we should propose a change to the `JWT` library and remove this custom code patch.
=> Ruby: fix conflict with JWT library

ruby/CHANGELOG.md, ruby/lib/truelayer-signing/jwt.rb, ruby/lib/truelayer-signing/signer.rb, ruby/lib/truelayer-signing/utils.rb, ruby/lib/truelayer-signing/verifier.rb, ruby/test/resources/failed-payment-expired-test-payload.json, ruby/test/test-truelayer-signing.rb
Verification of expired-payment webhook signatures is failing. This is
because the underlying `jwt` library expects the payload to be a JSON
object, but ours isn't, as per our request signing spec. This breaks
some code paths and the expiration verification was missed by our
manual/automated tests.
This disable expiration verification, as well as any other verification
that expects the payload to be a JSON object.
Jira ticket: https://truelayer.atlassian.net/browse/RSK-647
=> Ruby: disable expiration verification

request-signing-v2.md
Updating key generation bash commands to use openssl rather than Docker following feedback/confusion related to old commands. Also updated the wording/link for Console.
=> DOCS-973 Update request-signing-v2.md

nodejs/src/__tests__/usage.test.ts
A couple of error messages have changed in format following some
dependency updates. This updates the affected tests as needed.
=> NodeJS: fix failing tests

.github/workflows/csharp.yml
Since #228, the C# workflow will run for any changes in the C# code, the
shared test resources _and_ the C# workflow itself. This means that when
the library version does not change, the `publish` step simply fails,
which does not look good.
This updates the C# workflow so that it will only attempt to publish the
library when there is a `csharp/v**` tag being pushed. It does mean that
it now requires an additional manual step, but it also means that we can
more easily batch changes in each version bump, without the workflow
failing in between.
=> C#: publish on new tag only

.github/workflows/python.yml
Since #228, the Python workflow will run for any changes in the Python
code, the shared test resources _and_ the Python workflow itself. This
means that when the library version does not change, the `publish` step
simply fails, which does not look good.
This updates the Python workflow so that it will only attempt to publish
the library automatically when there is a version bump on `main`.
=> Python: publish on version bump only

python/CHANGELOG.md, python/pyproject.toml
There have been a couple of dependency updates since the last release,
so this bumps up the patch version. The revised workflow should pick up
the new package version and publish it automatically.
=> Python: release new patch version

csharp/CHANGELOG.md, csharp/src/Signer.cs, csharp/src/truelayer-signing.csproj, csharp/test/UsageTest.cs
Add `Signer.SignWithFunction(string kid, Func<string, Task<string>> signAsync)`  to allow consumers to pass a function which takes the signing payload and returns the signature. This allows signing to be delegated to an external key management service in the case that the library consumer does not have direct access to the private key.
The changes have been implemented in a non-breaking way for existing consumers.
Related PR for JS implementation: https://github.com/TrueLayer/truelayer-signing/pull/178
=> [PAYINS-464] [csharp] Add capability to sign with function

.github/workflows/php.yml, php/composer.json, php/tests/SignerTest.php, php/tests/VerifierTest.php
- switch from abandoned `web-token/jwt-*` to `web-token/jwt-library`
- remove support for end of life PHP versions
=> [PHP-74] New JWT library

.github/CODEOWNERS, csharp/src/Signer.cs, csharp/src/truelayer-signing.csproj, csharp/test/UsageTest.cs
Allow specifying a `jku` when creating a signature, which will be included in the JWS headers.
This is intended to be used for response signing and will point consumers to TrueLayer's JWKS for validating these signatures.
=> [PAYINS-600] [csharp] Allow specifying jku when creating signature

ruby/CHANGELOG.md, ruby/truelayer-signing.gemspec
Updates the gemspec file to comply with `Gemspec/AddRuntimeDependency`
(see https://github.com/rubygems/rubygems/issues/7799).
=> Ruby: fix linter error

python/CHANGELOG.md, python/pyproject.toml
Fixes https://github.com/TrueLayer/truelayer-signing/issues/331
=> Bump Python library from 0.3.5 to 0.3.6
