TrueLayer/truelayer-signing

php/.gitignore, php/.php-cs-fixer.php, php/composer.json, php/composer.lock, php/src/AbstractJws.php, php/src/Constants/CustomHeaders.php, php/src/Constants/TrueLayerSignatures.php, php/src/Contracts/Jws.php, php/src/Contracts/Signer.php, php/src/Contracts/Verifier.php, php/src/Exceptions/InvalidAlgorithmException.php, php/src/Exceptions/InvalidSignatureException.php, php/src/Exceptions/InvalidTrueLayerSignatureVersionException.php, php/src/Exceptions/RequestPathNotFoundException.php, php/src/Exceptions/RequiredHeaderMissingException.php, php/src/Exceptions/SignatureMustUseDetachedPayloadException.php, php/src/Signer.php, php/src/Util.php, php/src/Verifier.php, php/tests/MockData.php, php/tests/SignerTest.php, php/tests/UtilTest.php, php/tests/VerifierTest.php
This fixes a signing issue due to changing the header key casing, adds a code style fixer and a convenience method for easily signing PSR requests.
=> Php signing

go/CHANGELOG.md, go/README.md
Adds golang verify webhook snippet examples to their READMEs.
=> Add verifying webhooks readme examples for golang

java/CHANGELOG.md, java/README.md, java/gradle.properties
=> Set version 0.2.0

csharp/examples/webhook-server/ExampleWebhookServer.csproj, csharp/examples/webhook-server/Startup.cs, rust/examples/webhook-server/Cargo.toml
* Update rust webhook server dependencies
* Add c# webhook server jwks caching
=> Update webhook examples

java/.gitignore, java/README.md, java/examples/sign-request/README.md, java/examples/sign-request/build.gradle, java/examples/sign-request/src/main/java/com/truelayer/examples/sign_request/Program.java, java/examples/webhook-server/README.md, java/examples/webhook-server/build.gradle, java/examples/webhook-server/src/main/java/com/truelayer/signing/examples/webhook_server/WebhookServer.java, java/examples/webhook-server/src/main/java/com/truelayer/signing/examples/webhook_server/WebhookVerificationHandler.java, java/settings.gradle
Add examples for signing request and webhook verification using the java library
=> [MAP-1] Add java sign-request and webhook verification examples

nodejs/CHANGELOG.md, nodejs/src/__tests__/usage.test.ts, nodejs/src/lib.ts
=> nodejs: Add path validation

java/CHANGELOG.md, java/gradle.properties, java/lib/src/main/java/com/truelayer/signing/Signer.java, java/lib/src/main/java/com/truelayer/signing/Verifier.java, java/lib/src/test/java/com/truelayer/signing/UsageTest.java
https://github.com/TrueLayer/truelayer-signing/issues/69 for java
=> Path argument validation

python/LICENSE-APACHE, python/LICENSE-MIT, python/pyproject.toml
=> python: adds license + package info

rust/CHANGELOG.md, rust/Cargo.toml, rust/src/sign.rs, rust/src/verify.rs, rust/tests/usage.rs
=> rust: Add path validation assertions

rust/CHANGELOG.md, rust/Cargo.toml, rust/src/sign.rs, rust/src/verify.rs, rust/tests/usage.rs
=> Rust: verify handle path trailing /

nodejs/CHANGELOG.md, nodejs/package.json, nodejs/src/__tests__/usage.test.ts, nodejs/src/lib.ts, nodejs/yarn.lock
=>  nodejs: verify handle path trailing /

csharp/CHANGELOG.md, csharp/src/Verifier.cs, csharp/src/truelayer-signing.csproj, csharp/test/UsageTest.cs
=> csharp: verify handle path trailing /

java/CHANGELOG.md, java/gradle.properties, java/lib/src/main/java/com/truelayer/signing/VerifierFromJwks.java, java/lib/src/main/java/com/truelayer/signing/VerifierFromPublicKey.java, java/lib/src/test/java/com/truelayer/signing/UsageTest.java
=> java: verify handle path trailing /

.github/workflows/go.yml, go/CHANGELOG.md, go/sign/signer.go, go/tlsigning_test.go, go/verify/verifier.go
https://github.com/TrueLayer/truelayer-signing/issues/80 (option 2) for golang.
=> golang: verify handle path trailing /

php/CHANGELOG.md, php/LICENSE-APACHE, php/LICENSE-MIT
Composer doesnt follow the symlinks provided, so I've added the files.
=> Composer doesnt follow the symlinks provided

README.md, java7/gradle.properties, java7/settings.gradle
Meant to fix this subtle yet meaningful detail.
=> rootProject.name change

README.md
Updates `README.md` to list language libraries in alphabetical order.
=> Sort languages alphabetically

.github/workflows/java.yml, .github/workflows/java7.yml
Automate the release process by eliminating the needs for a manual release of the Nexus staging repository.
=> [EWT-83] Improve release process - Java

.github/workflows/csharp.yml, .github/workflows/go.yml, .github/workflows/java.yml, .github/workflows/java7.yml, .github/workflows/node.yml, .github/workflows/php.yml, .github/workflows/python.yml, .github/workflows/ruby.yml, .github/workflows/rust.yml
Sometimes dependency updates include changes to the GitHub workflow
files and in those cases the related tests aren't run. This updates all
workflow so that they also run when updated themselves.
=> Run actions on workflow changes

rust/src/http.rs, rust/src/sign/mod.rs, rust/src/verify/mod.rs
Adds `delete`, `put`, and `patch` to list of HTTP methods.
=> add other http methods

rust/Cargo.toml, rust/src/sign/mod.rs, rust/src/verify/mod.rs
The Body will no longer be ignored for requests method GET or DELETE.
=> rust: allow reponse GET body sign/verify

csharp/examples/sign-request/README.md, go/examples/sign-request/README.md, java/examples/sign-request/README.md, java7/examples/sign-request/README.md, nodejs/examples/sign-request/README.md, nodejs/src/__tests__/usage.test.js, nodejs/src/__tests__/usage.test.ts, python/examples/sign-request/README.md, ruby/examples/sign-request/README.md, rust/examples/sign-request/README.md
- test: add tests for nested JSON and special chars to the nodejs lib
- docs: fix  broken docs link for generating payments access tokens
=> nodejs: add tests for nested JSON and special chars
